### ISSUE TITLE
Add CNM as first Organization

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/CNMApp#13]
## User Report
CHAI will provide the text

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot804991405.jpg)
## Device Info
```
Time Stamp: 2018-03-30T12:09:35 UTC
App Version: 0.3.0 (52)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: SAMSUNG
Device Model: SM-G930F
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by ifoche** [comment]
Can you please develop on this? I don't understand what first organisation means here. Thanks!

**Comment by ppagalday** [comment]
@ifoche sorry but the screenshot did not gather the issue. I mean that when you click in the app on "About" at the right top corner, the first organization mentioned should be CNM since they will be the owners of the system. We can provide you with the description of what should say.

**Comment by ifoche** [comment]
@ppagalday sure, please just send me the final text by email and we will introduce it there. If you can provide it both in Khmer and English that would be perfect. Thank you!

**Comment by ppagalday** [comment]
@ifoche Can we keep it open so we do a few changes on that in the next release, sorry for that, is our fault, we should have provide you the document, but thank you for that

**Comment by ifoche** [comment]
sure! moving it ready so we can take it into account for the next release

**Comment by ifoche** [comment]
@ppagalday any update on this? do you want us to change this text? We would be happy to do it if you want. Otherwise, we can just move it to backlog if you prefer.

**Comment by ppagalday** [comment]
@ifoche “National Center for Parasitology, Entomology, and Malaria Control (CNM)
Lead implementation and conceptualization
CNM has led the strategy development and implementation of all malaria activities in Cambodia with the current targets of Pf elimination by 2020 and Pv elimination by 2025. A core strategy of the CNM’s Malaria Elimination Action Framework (MEAF) is the strengthening of Surveillance systems to facilitate the implementation of all elimination activities.”

Yes, so we just put CNM first on the text and add the above text
