### ISSUE TITLE
Adapt HC App to 11 inch screen

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#14]
HCs use an 11 inch tablet, the current structure is great for smartphones but letters are too small for Tablets. Wonder if we could adapt the design to 11'' screen for the next release (only for HC)

**Comment by ppagalday** [comment]
![Treatment.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abe1feeef024e0011d00e10/125516c66e82c728ace21e0d46dc869f22968eac81fdfd0fe64de29b234324676b5ee17e2983b170bc1323540c594faa12585f46faf8db2ca1e23d62964e49bc8f3900299f7744eeaa880dbe06b0218e4d81bebe8f48c0e93f24e099c2.png) Add also the treatment name

**Comment by ifoche** [comment]
In settings there's an option "Customize fonts". Did you try to configure it bigger?

**Comment by ppagalday** [comment]
Perfect! That works, we can close it
