### ISSUE TITLE
Change the Treatment screen picture

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#18]

**Comment by ifoche** [comment]
can you develop more on this? do you have anything in mind?

**Comment by ppagalday** [comment]
@ifoche sorry I thought I uploaded the picture

**Comment by ppagalday** [comment]
![Treatment.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abe1feeef024e0011d00e10/125516c66e82c728ace21e0d46dc869f22968eac81fdfd0fe64de29b234324676b5ee17e2983b170bc1323540c594faa12585f46faf8db2ca1e23d62964e49bc8f3900299f7744eeaa880dbe08b0218e4d80b5bd824ac5ec3d23e799c2.png)

**Comment by ppagalday** [comment]
adding the treatment name

**Comment by ppagalday** [comment]
To summarize we would like the image to be the number of pills (3 small dots if it is 25/50, 3 big dots if it is 100/200, 6 small dots if is 35/50, 6 big dots if it is 100/200 + Different color pill for PQ). Keeping still the name of the option set (treatment provided) and adding on the left side those faces, which are the picture that appears on the box provided to the patient. This is very important because with the current pictures users keep introducing the treatment wrong

**Comment by ppagalday** [comment]
![treatment choice.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abe1feeef024e0011d00e10/125516c66e82c728ace21e0d46fc869f22968eac81fdff40ac52f9972c046b313916ac217586f76ae5002e58095d46ff40505a17faf88f78a6b63e768b0e0cea856c4d68d47f40f2ecdd42e64bef62994597b7bb804dc5ea3a23e0898f4d38160d1a9bb2.png)
