### ISSUE TITLE
Add Case Date as a question

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#22]
Have you reported the case within 24 hours? Yes/No if No -> Ask the case date

**Comment by ppagalday** [comment]
@ifoche give us 24 hours for this one that we might simplify it based on conversations with the government tomorrow please

**Comment by ifoche** [comment]
Sure, no worries, please let me know whenever you have finished your conversations and you have definitive functional requirements

**Comment by ppagalday** [comment]
@ifoche after talking with Jose, let's do the question just as a date picker as the last question for both VMWs and HCs
