### ISSUE TITLE
VMW app changes to HC app

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#31]
It might be related to the permissions, app suddenly changed for 6 org units to HC suddenly, device tried to access location and changed configuration to HC while logged in as a Village

**Comment by ppagalday** [comment]
@ifoche seems the org unit groups are configured right in the web

**Comment by ifoche** [comment]
@ppagalday do you have the list of OUs to share so we can test and try to replicate it?

**Comment by ppagalday** [comment]
@ifoche yes, the OU are the Villages under Chieb (HC040110): Especially, O Kél (VL0408080800) and La (VL0408080200). I can provide you the full list if you want

**Comment by ppagalday** [comment]
@ifoche That happened again with O Kel Org Unit
