### ISSUE TITLE
Treatment is not sent to the server

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#32]

**Comment by ppagalday** [comment]
@ifoche seems the DE treatment with Dosage was not added to the program. I have added it to VMW program, will the app synchronize with this data element?

**Comment by ifoche** [comment]
@ppagalday the app was already sending the information for that DE (so the server was probably ignoring it). It should just start working without any other problem

**Comment by ppagalday** [comment]
@ifoche closing it, you werte right! Thanks
