### ISSUE TITLE
Cases not uploaded in the background

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#36]

**Comment by ifoche** [comment]
@ppagalday @josemp10 the app is actually sending all the cases also when it's in background. So the only 2 situations that we can imagine where this could be happening are:
1) If the app was never opened (e.g. after a device reboot)
2) If the device has very few memory, so the Android tasks manager decide to close the app

As a solution to 1) we could explore to define a permission to automatically boot the app on device start...if that's the approach you prefer us to take. Re 2) there's nothing that we can do if the app's killed. Do you have an idea of which kind of devices are suffering from this? Is it something that you can replicate in a consistent way? Thanks!!

**Comment by ppagalday** [comment]
@ifoche  let me check them out so I can provide more details, we will double check again in the 4.4 devices that have this issues
