### ISSUE TITLE
Change the URL of the server

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/CNMApp#43]
New URL: https://sandbox.cnm-mis.org/

**Comment by ifoche** [comment]
Looks like the new server has a concrete version of nginx that is producing an exception with okHttp, so we're not changing the URL by now.

**Comment by josemp10** [comment]
@ifoche  Im going to ask BAO today for copying the database from cnm-android to the sandbox server? It should be ready by Monday. Is that ok?

**Comment by ifoche** [comment]
We found a way to resolve the problem of incompatibility between okHttp version and nginx (actually, upgrading okHttp version and changing the syntax of all related code to the newest one)
