### ISSUE TITLE
Village change to HC app

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/CNMApp#44]
## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1651615048.jpg)
## Device Info
```
Time Stamp: 2018-05-15T20:59:44 UTC
App Version: 0.4.1 (55)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: SAMSUNG
Device Model: SM-G930F
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by ifoche** [comment]
@ppagalday can you confirm this is no longer happening since the last version?

**Comment by ppagalday** [comment]
@ifoche so far has not happened again, we are doing supervision visits today so we will confirm

**Comment by ppagalday** [comment]
@ifoche it happens similar, when configuring Moung OU with the IMEI gives an error and loads Moung as HC when is  a village

**Comment by ifoche** [comment]
@ppagalday it makes sense. If the auto-configure fails, the system doesn't know if the OU is a Village or a HC, and it assumes HC by default. But when the auto-configuration works, it doesn't jump to HC, right?

**Comment by ppagalday** [comment]
@ifoche when the configuration works, it does not jump anymore to HC, solving 46 I think we can close this one

**Comment by ifoche** [comment]
great, thanks!
