### ISSUE TITLE
Cases disappear when on the list of "Pending to be upload" and never sent to the system

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#46]

**Comment by ifoche** [comment]
@ppagalday is there anything in special in the surveys that disappear? Have you found a way to consistently replicate it?

**Comment by ppagalday** [comment]
@ifoche I sent a video to Jose of the issue but we have not been able to replicate it yet

**Comment by ppagalday** [comment]
what disappears is the case  from the list of pending to be uploaded

**Comment by ppagalday** [comment]
@ifoche @josemp10 Hi both, I found how to replicate the error, some org units Moung and La are giving errors when autoconfiguring, so when the user reports a case, it disappears quickly from the list, I think when the case  is sent, since there is an error with the config coming from the server, returns an error but the app treats it as sent. Could you please replicate it and find out whit the autoconfigure error is happening? it does not happen with all org units. Im scared that if this error keeps happening we are losing cases coming to the server

**Comment by ifoche** [comment]
@ppagalday I think Jose wanted me to wait until he can talk with you. It looks like you have a consistent way to replicate it. Can you provide the OU path to an OU experimenting the problem? BTW, one of the reasons for an auto-configure problem (just in case) is when the device has more than one SIM slots. That implies having more than one IMEI numbers, so you may be introducing the wrong IMEI in the phone number field.

**Comment by ppagalday** [comment]
@ifoche I can talk to @josemp10 later today, I will be with him. The OU with a problem were the one with the following IDs: 0408080200, 0408021100,0408040700. The problem came on 3 devices, one tablet with only one SIM, one phone with two SIMs (we chose the one that was working), and with my personal phone that has only one SIM . The auto-configuration error also happens when I try to download the metadata for those OUs with Username/password, I think if the auto-config error is solved,  will solve the cases disappearing .

**Comment by josemp10** [comment]
At the end this one was related to a configuration issue in the server. @ppagalday  can you confirm that this is not happening anymore?

**Comment by ppagalday** [comment]
@josemp10 @ifoche solved! Thanks, closing the issue
