### ISSUE TITLE
Cases do not upload after network interruption in VMW app

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#50]
That only happens when the login in the VMW app is done with Username and Password, the next steps will help recreate the issue:

1.  Login to the desired VMW village with the username and password
2.  Exit app and then turn off all data on your device 
3.  Return to the app with data still off (this is a common use case for VMWs) and report a case. As expected it will not upload since there is not data
4.  Exit app and turn on the phone’s data
5.  Return to the app to upload the case. You will notice it will not upload. In some cases the case will flicker where it would disappear and then return. I waited 10+ minutes and the case would not upload. You can try adding another case at this point but it did not upload for me either

**Comment by ifoche** [comment]
@ppagalday just in case but, after the manual login, you're selecting the desired OU and waiting for the app to finish the second metadata download, right?

**Comment by ifoche** [comment]
And another possibility...It is not a refresh issue right? I mean, if you change the tab and go back again to the unsent list, it's still there, right?

**Comment by ifoche** [comment]
In case my previous questions still don't help, could you please tell me which OU you are using and send me the DB of a user just having this problem for us to analyze it? Thanks!

**Comment by ppagalday** [comment]
@ifoche Yes, exactly, we select the OU and wait for metadata to Download, the OU we used is Banteay Neang (VL0102010300). Already sent you the dB of one of the devices in the field! Thanks
