### ISSUE TITLE
VMW cases do not appear in the Web

### ISSUE THREAD

**Issue by ppagalday** [EyeSeeTea/CNMApp#7]
No VMW events are sent

**Comment by ifoche** [comment]
@ppagalday, can you develop a bit more on this? Which user were you using? I guess you're using dhis2.asia/cnm_android server. Can you send your DB for us to analyze the concrete situation? Thanks!

**Comment by ppagalday** [comment]
@ifoche I was using my user ppagalday and the cnm_android server. My phone IMEI is assigned to Bantey Neang (VL0102010300), when I report a case, the case is never uploaded, after a while they disappear from  the main screen and there are no events in the Web for that org unit. Sent it to you via email

**Comment by ifoche** [comment]
Hi @ppagalday, it was a server configuration issue. The program was not assigned to that OU. It should work now. Can you confirm?

**Comment by ppagalday** [comment]
@ifoche I  can see the cases in the Malaria-VMW Program right now, also, I realized when I have cases pending to be uploaded and I auto-configure the user, the cases that were pending to be uploaded disappear.  It takes a few minutes to upload the cases for VMWs while HC are a bit faster, but it might not be important right now. Thanks!

**Comment by ifoche** [comment]
Good! Re the pending cases that disappear in auto-configuration, that is something you might want to warn the users about. An auto-configuration is a user authentication, and every logout-login implies the deletion of any data from the user that log out. So I would recommend not to auto-configure while you're in normal operation. I guess, however, that this is a corner case a normal user won't experiment, but just in case...

If you consider this task as done, could you please move the issue to "Done" column? Thanks!

**Comment by ppagalday** [comment]
Consider it done, but does not let me move it to Done, so go ahead!

**Comment by ifoche** [comment]
ouch! That's weird... Did you accept the invitation to be part of the CNM Testers group in github? That could be the reason. I close it. Thank you!

**Comment by ppagalday** [comment]
@ifoche this was solved but we have problems with just one device that is not able to send the events to the server. Should I send you the db again?
