### ISSUE TITLE
Remove Stock for VMWs

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/CNMApp#8]
## User Report
VMWs should not have access to stock

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot800154616.jpg)
## Device Info
```
Time Stamp: 2018-03-30T11:38:15 UTC
App Version: 0.3.0 (52)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: SAMSUNG
Device Model: SM-G930F
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by ppagalday** [comment]
@ifoche VMW have access again to stock in the new release
