### ISSUE TITLE
Villages do not appear in the org unit list

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/CNMApp#9]
## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot729776232.jpg)
## Device Info
```
Time Stamp: 2018-03-30T11:40:34 UTC
App Version: 0.3.0 (52)
Install Source: Package Installer
Android Version: 7.0 (24)
Device Manufacturer: SAMSUNG
Device Model: SM-G930F
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by ppagalday** [comment]
When the IMEI is introduced on the Org Unit phone field it does work. But when we have an user with access to only Villages as Org Units they are not loaded in the app to be selected, same applies when the user have access to both HC and Vll

**Comment by dhis2-android** [comment]
In case it helps: Health Centers and VMWs are it different level in the org. unit tree, so maybe the app is only returning the org. units at the HC level?

**Comment by ppagalday** [comment]
Exactly, but even when I have an user with only access to a Village it does not show it
